version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shippify_db
      MYSQL_USER: shippify_user
      MYSQL_PASSWORD: shippify_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    networks:
      - app_network

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge
